-- StockFamily historical market database for Supabase/Postgres.
create table if not exists stocks (
  id bigint generated by default as identity primary key,
  code varchar(20) not null unique,
  name text not null default '',
  remarks text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists daily_stock_data (
  id bigint generated by default as identity primary key,
  stock_id bigint not null references stocks(id) on delete cascade,
  trade_date date not null,
  previous_price numeric(20,4) not null default 0,
  open numeric(20,4) not null default 0,
  first_trade numeric(20,4) not null default 0,
  high numeric(20,4) not null default 0,
  low numeric(20,4) not null default 0,
  close numeric(20,4) not null default 0,
  change_price numeric(20,4) not null default 0,
  volume bigint not null default 0,
  value numeric(30,2) not null default 0,
  frequency bigint not null default 0,
  index_individual numeric(20,6) not null default 0,
  offer numeric(20,4) not null default 0,
  offer_volume bigint not null default 0,
  bid numeric(20,4) not null default 0,
  bid_volume bigint not null default 0,
  listed_shares bigint not null default 0,
  tradeable_shares bigint not null default 0,
  weight_for_index numeric(30,6) not null default 0,
  foreign_sell bigint not null default 0,
  foreign_buy bigint not null default 0,
  non_regular_volume bigint not null default 0,
  non_regular_value numeric(30,2) not null default 0,
  non_regular_frequency bigint not null default 0,
  created_at timestamptz not null default now(),
  unique(stock_id, trade_date)
);

create index if not exists idx_daily_trade_date on daily_stock_data(trade_date);
create index if not exists idx_daily_stock_date on daily_stock_data(stock_id, trade_date);

create table if not exists upload_batches (
  id bigint generated by default as identity primary key,
  filename text,
  trade_date date not null unique,
  row_count integer not null default 0,
  uploaded_at timestamptz not null default now()
);

alter table stocks enable row level security;
alter table daily_stock_data enable row level security;
alter table upload_batches enable row level security;

create or replace function replace_market_snapshot(p_trade_date date, p_filename text, p_rows jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare r jsonb; v_stock_id bigint; v_count integer := 0;
begin
  -- Delete the whole date first. This guarantees re-upload of the same date replaces it.
  delete from daily_stock_data where trade_date = p_trade_date;

  for r in select * from jsonb_array_elements(p_rows) loop
    insert into stocks(code, name, remarks, updated_at)
    values (r->>'code', coalesce(r->>'name',''), coalesce(r->>'remarks',''), now())
    on conflict(code) do update set name=excluded.name, remarks=excluded.remarks, updated_at=now()
    returning id into v_stock_id;

    insert into daily_stock_data(
      stock_id, trade_date, previous_price, open, first_trade, high, low, close, change_price,
      volume, value, frequency, index_individual, offer, offer_volume, bid, bid_volume,
      listed_shares, tradeable_shares, weight_for_index, foreign_sell, foreign_buy,
      non_regular_volume, non_regular_value, non_regular_frequency
    ) values (
      v_stock_id, p_trade_date,
      coalesce((r->>'previous_price')::numeric,0), coalesce((r->>'open')::numeric,0), coalesce((r->>'first_trade')::numeric,0),
      coalesce((r->>'high')::numeric,0), coalesce((r->>'low')::numeric,0), coalesce((r->>'close')::numeric,0), coalesce((r->>'change_price')::numeric,0),
      coalesce((r->>'volume')::bigint,0), coalesce((r->>'value')::numeric,0), coalesce((r->>'frequency')::bigint,0),
      coalesce((r->>'index_individual')::numeric,0), coalesce((r->>'offer')::numeric,0), coalesce((r->>'offer_volume')::bigint,0),
      coalesce((r->>'bid')::numeric,0), coalesce((r->>'bid_volume')::bigint,0), coalesce((r->>'listed_shares')::bigint,0),
      coalesce((r->>'tradeable_shares')::bigint,0), coalesce((r->>'weight_for_index')::numeric,0),
      coalesce((r->>'foreign_sell')::bigint,0), coalesce((r->>'foreign_buy')::bigint,0),
      coalesce((r->>'non_regular_volume')::bigint,0), coalesce((r->>'non_regular_value')::numeric,0), coalesce((r->>'non_regular_frequency')::bigint,0)
    );
    v_count := v_count + 1;
  end loop;

  insert into upload_batches(filename, trade_date, row_count, uploaded_at)
  values(p_filename, p_trade_date, v_count, now())
  on conflict(trade_date) do update set filename=excluded.filename, row_count=excluded.row_count, uploaded_at=now();

  return jsonb_build_object('trade_date', p_trade_date, 'rows', v_count, 'replaced', true);
end $$;

create or replace function market_period_summary(p_start_date date, p_end_date date)
returns table(
  code varchar, name text, latest_date date, latest_close numeric, period_high numeric, period_low numeric,
  foreign_buy numeric, foreign_sell numeric, foreign_net numeric, volume numeric, value numeric, frequency numeric, active_days bigint
) language sql stable as $$
  with ranked as (
    select s.code, s.name, d.trade_date, d.close, d.high, d.low, d.foreign_buy, d.foreign_sell, d.volume, d.value, d.frequency,
           row_number() over(partition by s.id order by d.trade_date desc) rn
    from daily_stock_data d join stocks s on s.id=d.stock_id
    where (p_start_date is null or d.trade_date>=p_start_date) and (p_end_date is null or d.trade_date<=p_end_date)
  )
  select code, max(name) name, max(trade_date) latest_date,
         max(close) filter(where rn=1) latest_close, max(high) period_high, min(low) period_low,
         sum(foreign_buy) foreign_buy, sum(foreign_sell) foreign_sell,
         sum(foreign_buy-foreign_sell) foreign_net, sum(volume) volume, sum(value) value, sum(frequency) frequency,
         count(*) filter(where volume>0) active_days
  from ranked group by code order by code;
$$;


grant execute on function replace_market_snapshot(date, text, jsonb) to service_role;
grant execute on function market_period_summary(date, date) to service_role;
